apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-openvpn
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: openvpn
  mountOptions:
    - hard
  #   - nfsvers=4.1
  nfs:
    path: /tank/nfs/iso/k8s
    server: 192.168.1.7