apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-grafana
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  #   - nfsvers=4.1
  nfs:
    path: /tank/nfs/iso/k8s
    server: 192.168.1.7