---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openvpn
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
  volumeName: "pv-nfs-openvpn"
  storageClassName: "openvpn"